name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  test: # make sure the action works on a clean machine without building

    defaults:
      run:
        shell: bash -l {0}  # for setup-miniconda

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          channel-priority: strict
          python-version: '3.10'

      - uses: ./
        name: "Run action from local source (./)"
        with:
          shell: bash -el {0}
          run: |
            env
            which python
            conda run which python
            echo "this is where your commands would run"
            echo "multiple commands are entered as multi-line input"
          linux-setup-delay: 500
